env:
  domain_name: "walker"
  task_name: "run"

dreamer:
  state_dims: 512
  latent_dims: 512
  o_feature_dim: 32
  img_h : 64
  img_w : 64
  reward_dim: 1
  gamma: 0.99
  lambda_: 0.95
  batch_size: 8
  batch_train_freq: 10
  buffer_size: 100000000
  sample_steps: 50
  steps_of_sampling: 500
  horizon: 10

training:
  timesteps: 10000
  num_points: 50
  data_length: 50